# Generated by Django 2.2.6 on 2019-10-25 20:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0003_employee_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='monday_end',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='employee',
            name='monday_start',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
