# Generated by Django 2.2.6 on 2019-11-02 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0006_auto_20191028_0012'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='weekday_close',
            field=models.TimeField(default='23:00:00'),
        ),
        migrations.AddField(
            model_name='location',
            name='weekday_open',
            field=models.TimeField(default='08:00:00'),
        ),
        migrations.AddField(
            model_name='location',
            name='weekend_close',
            field=models.TimeField(default='17:00:00'),
        ),
        migrations.AddField(
            model_name='location',
            name='weekend_open',
            field=models.TimeField(default='10:00:00'),
        ),
    ]
