# Generated by Django 2.2.6 on 2019-11-05 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0007_auto_20191102_1839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='weekday_close',
            field=models.TimeField(default='10:00:00'),
        ),
        migrations.AlterField(
            model_name='location',
            name='weekend_close',
            field=models.TimeField(default='10:00:00'),
        ),
        migrations.AlterField(
            model_name='location',
            name='weekend_open',
            field=models.TimeField(default='08:00:00'),
        ),
    ]
