# Generated by Django 2.2.6 on 2019-11-05 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0008_auto_20191105_1846'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='fri_close',
            field=models.TimeField(default='08:00:00'),
        ),
        migrations.AddField(
            model_name='location',
            name='fri_open',
            field=models.TimeField(default='08:00:00'),
        ),
        migrations.AddField(
            model_name='location',
            name='mon_close',
            field=models.TimeField(default='08:00:00'),
        ),
        migrations.AddField(
            model_name='location',
            name='mon_open',
            field=models.TimeField(default='08:00:00'),
        ),
        migrations.AddField(
            model_name='location',
            name='sat_close',
            field=models.TimeField(default='08:00:00'),
        ),
        migrations.AddField(
            model_name='location',
            name='sat_open',
            field=models.TimeField(default='08:00:00'),
        ),
        migrations.AddField(
            model_name='location',
            name='sun_close',
            field=models.TimeField(default='08:00:00'),
        ),
        migrations.AddField(
            model_name='location',
            name='sun_open',
            field=models.TimeField(default='08:00:00'),
        ),
        migrations.AddField(
            model_name='location',
            name='thu_close',
            field=models.TimeField(default='08:00:00'),
        ),
        migrations.AddField(
            model_name='location',
            name='thu_open',
            field=models.TimeField(default='08:00:00'),
        ),
        migrations.AddField(
            model_name='location',
            name='tue_close',
            field=models.TimeField(default='08:00:00'),
        ),
        migrations.AddField(
            model_name='location',
            name='tue_open',
            field=models.TimeField(default='08:00:00'),
        ),
        migrations.AddField(
            model_name='location',
            name='wed_close',
            field=models.TimeField(default='08:00:00'),
        ),
        migrations.AddField(
            model_name='location',
            name='wed_open',
            field=models.TimeField(default='08:00:00'),
        ),
    ]
