# Generated by Django 2.2.7 on 2019-11-06 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0009_auto_20191105_1853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='weekday_close',
            field=models.TimeField(default='08:00:00'),
        ),
        migrations.AlterField(
            model_name='location',
            name='weekend_close',
            field=models.TimeField(default='08:00:00'),
        ),
    ]
