# Generated by Django 2.2.6 on 2019-11-17 20:25

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0010_auto_20191106_0604'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='weekday_close',
        ),
        migrations.RemoveField(
            model_name='location',
            name='weekday_open',
        ),
        migrations.RemoveField(
            model_name='location',
            name='weekend_close',
        ),
        migrations.RemoveField(
            model_name='location',
            name='weekend_open',
        ),
        migrations.CreateModel(
            name='EmployeeAssignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('end', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='empassign_emp', to='scheduler.Employee')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='empassign_loc', to='scheduler.Location')),
            ],
        ),
    ]
