# Generated by Django 2.2.6 on 2019-11-17 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0012_remove_employeeassignment_end'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='mon_close',
            new_name='monday_close',
        ),
        migrations.RenameField(
            model_name='location',
            old_name='mon_open',
            new_name='monday_open',
        ),
    ]
