# Generated by Django 2.2.6 on 2019-11-18 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0013_auto_20191117_2335'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeassignment',
            name='current',
            field=models.BooleanField(default=False),
        ),
    ]
