# Generated by Django 2.2.7 on 2019-11-21 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0014_employeeassignment_current'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='email',
            field=models.CharField(default='joe@gmail.com', max_length=30),
        ),
        migrations.AddField(
            model_name='employee',
            name='password',
            field=models.CharField(default='password', max_length=30),
        ),
    ]
