# Generated by Django 2.2.7 on 2019-11-21 03:39

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0014_employeeassignment_current'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_date', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('return_date', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('status', models.CharField(max_length=20)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emp', to='scheduler.Employee')),
            ],
        ),
    ]
