# Generated by Django 2.2.7 on 2019-11-21 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0015_request'),
        ('scheduler', '0015_auto_20191121_0634'),
    ]

    operations = [
    ]
