# Generated by Django 2.2.6 on 2019-11-21 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0015_auto_20191121_0416'),
        ('scheduler', '0016_merge_20191121_0645'),
    ]

    operations = [
    ]
