# Generated by Django 2.2.6 on 2019-11-21 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0017_merge_20191121_0748'),
        ('scheduler', '0015_event'),
    ]

    operations = [
    ]
